#!/usr/bin/env bash
#
    updates=$(emerge -pvuND @world | \
        awk '/Total:/ {print $2}')

    if [ "$updates" -gt 0 ]; then
        echo "  $updates Pkgs  | "
    elif [ "$updates" == 0 ]; then
        echo ""
    fi